/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalIndexRouteImport } from './routes/internal/index'
import { Route as GruppeNeuRouteImport } from './routes/gruppe/neu'
import { Route as GruppeGroupSlugIndexRouteImport } from './routes/gruppe/$groupSlug/index'
import { Route as GruppeGroupSlugEinstellungenRouteImport } from './routes/gruppe/$groupSlug/einstellungen'
import { Route as GruppeGroupSlugTurnierNeuRouteImport } from './routes/gruppe/$groupSlug/turnier/neu'
import { Route as GruppeGroupSlugTurnierTournamentIdIndexRouteImport } from './routes/gruppe/$groupSlug/turnier/$tournamentId/index'
import { Route as GruppeGroupSlugTurnierTournamentIdAdminRouteImport } from './routes/gruppe/$groupSlug/turnier/$tournamentId/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalIndexRoute = InternalIndexRouteImport.update({
  id: '/internal/',
  path: '/internal/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppeNeuRoute = GruppeNeuRouteImport.update({
  id: '/gruppe/neu',
  path: '/gruppe/neu',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppeGroupSlugIndexRoute = GruppeGroupSlugIndexRouteImport.update({
  id: '/gruppe/$groupSlug/',
  path: '/gruppe/$groupSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruppeGroupSlugEinstellungenRoute =
  GruppeGroupSlugEinstellungenRouteImport.update({
    id: '/gruppe/$groupSlug/einstellungen',
    path: '/gruppe/$groupSlug/einstellungen',
    getParentRoute: () => rootRouteImport,
  } as any)
const GruppeGroupSlugTurnierNeuRoute =
  GruppeGroupSlugTurnierNeuRouteImport.update({
    id: '/gruppe/$groupSlug/turnier/neu',
    path: '/gruppe/$groupSlug/turnier/neu',
    getParentRoute: () => rootRouteImport,
  } as any)
const GruppeGroupSlugTurnierTournamentIdIndexRoute =
  GruppeGroupSlugTurnierTournamentIdIndexRouteImport.update({
    id: '/gruppe/$groupSlug/turnier/$tournamentId/',
    path: '/gruppe/$groupSlug/turnier/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GruppeGroupSlugTurnierTournamentIdAdminRoute =
  GruppeGroupSlugTurnierTournamentIdAdminRouteImport.update({
    id: '/gruppe/$groupSlug/turnier/$tournamentId/admin',
    path: '/gruppe/$groupSlug/turnier/$tournamentId/admin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gruppe/neu': typeof GruppeNeuRoute
  '/internal/': typeof InternalIndexRoute
  '/gruppe/$groupSlug/einstellungen': typeof GruppeGroupSlugEinstellungenRoute
  '/gruppe/$groupSlug/': typeof GruppeGroupSlugIndexRoute
  '/gruppe/$groupSlug/turnier/neu': typeof GruppeGroupSlugTurnierNeuRoute
  '/gruppe/$groupSlug/turnier/$tournamentId/admin': typeof GruppeGroupSlugTurnierTournamentIdAdminRoute
  '/gruppe/$groupSlug/turnier/$tournamentId/': typeof GruppeGroupSlugTurnierTournamentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gruppe/neu': typeof GruppeNeuRoute
  '/internal': typeof InternalIndexRoute
  '/gruppe/$groupSlug/einstellungen': typeof GruppeGroupSlugEinstellungenRoute
  '/gruppe/$groupSlug': typeof GruppeGroupSlugIndexRoute
  '/gruppe/$groupSlug/turnier/neu': typeof GruppeGroupSlugTurnierNeuRoute
  '/gruppe/$groupSlug/turnier/$tournamentId/admin': typeof GruppeGroupSlugTurnierTournamentIdAdminRoute
  '/gruppe/$groupSlug/turnier/$tournamentId': typeof GruppeGroupSlugTurnierTournamentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gruppe/neu': typeof GruppeNeuRoute
  '/internal/': typeof InternalIndexRoute
  '/gruppe/$groupSlug/einstellungen': typeof GruppeGroupSlugEinstellungenRoute
  '/gruppe/$groupSlug/': typeof GruppeGroupSlugIndexRoute
  '/gruppe/$groupSlug/turnier/neu': typeof GruppeGroupSlugTurnierNeuRoute
  '/gruppe/$groupSlug/turnier/$tournamentId/admin': typeof GruppeGroupSlugTurnierTournamentIdAdminRoute
  '/gruppe/$groupSlug/turnier/$tournamentId/': typeof GruppeGroupSlugTurnierTournamentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gruppe/neu'
    | '/internal/'
    | '/gruppe/$groupSlug/einstellungen'
    | '/gruppe/$groupSlug/'
    | '/gruppe/$groupSlug/turnier/neu'
    | '/gruppe/$groupSlug/turnier/$tournamentId/admin'
    | '/gruppe/$groupSlug/turnier/$tournamentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gruppe/neu'
    | '/internal'
    | '/gruppe/$groupSlug/einstellungen'
    | '/gruppe/$groupSlug'
    | '/gruppe/$groupSlug/turnier/neu'
    | '/gruppe/$groupSlug/turnier/$tournamentId/admin'
    | '/gruppe/$groupSlug/turnier/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/gruppe/neu'
    | '/internal/'
    | '/gruppe/$groupSlug/einstellungen'
    | '/gruppe/$groupSlug/'
    | '/gruppe/$groupSlug/turnier/neu'
    | '/gruppe/$groupSlug/turnier/$tournamentId/admin'
    | '/gruppe/$groupSlug/turnier/$tournamentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GruppeNeuRoute: typeof GruppeNeuRoute
  InternalIndexRoute: typeof InternalIndexRoute
  GruppeGroupSlugEinstellungenRoute: typeof GruppeGroupSlugEinstellungenRoute
  GruppeGroupSlugIndexRoute: typeof GruppeGroupSlugIndexRoute
  GruppeGroupSlugTurnierNeuRoute: typeof GruppeGroupSlugTurnierNeuRoute
  GruppeGroupSlugTurnierTournamentIdAdminRoute: typeof GruppeGroupSlugTurnierTournamentIdAdminRoute
  GruppeGroupSlugTurnierTournamentIdIndexRoute: typeof GruppeGroupSlugTurnierTournamentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/': {
      id: '/internal/'
      path: '/internal'
      fullPath: '/internal/'
      preLoaderRoute: typeof InternalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppe/neu': {
      id: '/gruppe/neu'
      path: '/gruppe/neu'
      fullPath: '/gruppe/neu'
      preLoaderRoute: typeof GruppeNeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppe/$groupSlug/': {
      id: '/gruppe/$groupSlug/'
      path: '/gruppe/$groupSlug'
      fullPath: '/gruppe/$groupSlug/'
      preLoaderRoute: typeof GruppeGroupSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppe/$groupSlug/einstellungen': {
      id: '/gruppe/$groupSlug/einstellungen'
      path: '/gruppe/$groupSlug/einstellungen'
      fullPath: '/gruppe/$groupSlug/einstellungen'
      preLoaderRoute: typeof GruppeGroupSlugEinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppe/$groupSlug/turnier/neu': {
      id: '/gruppe/$groupSlug/turnier/neu'
      path: '/gruppe/$groupSlug/turnier/neu'
      fullPath: '/gruppe/$groupSlug/turnier/neu'
      preLoaderRoute: typeof GruppeGroupSlugTurnierNeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppe/$groupSlug/turnier/$tournamentId/': {
      id: '/gruppe/$groupSlug/turnier/$tournamentId/'
      path: '/gruppe/$groupSlug/turnier/$tournamentId'
      fullPath: '/gruppe/$groupSlug/turnier/$tournamentId/'
      preLoaderRoute: typeof GruppeGroupSlugTurnierTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gruppe/$groupSlug/turnier/$tournamentId/admin': {
      id: '/gruppe/$groupSlug/turnier/$tournamentId/admin'
      path: '/gruppe/$groupSlug/turnier/$tournamentId/admin'
      fullPath: '/gruppe/$groupSlug/turnier/$tournamentId/admin'
      preLoaderRoute: typeof GruppeGroupSlugTurnierTournamentIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GruppeNeuRoute: GruppeNeuRoute,
  InternalIndexRoute: InternalIndexRoute,
  GruppeGroupSlugEinstellungenRoute: GruppeGroupSlugEinstellungenRoute,
  GruppeGroupSlugIndexRoute: GruppeGroupSlugIndexRoute,
  GruppeGroupSlugTurnierNeuRoute: GruppeGroupSlugTurnierNeuRoute,
  GruppeGroupSlugTurnierTournamentIdAdminRoute:
    GruppeGroupSlugTurnierTournamentIdAdminRoute,
  GruppeGroupSlugTurnierTournamentIdIndexRoute:
    GruppeGroupSlugTurnierTournamentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
